#!/usr/bin/env python3
"""Generate port/port_tracker_fusions.inc: one label per kinstone fusion, and
names for the NPC and enemy ids that fuse (the fuser tables name a fuser only
by entity id).

The check tracker lists all 100 fusions. Their status comes from the save at
runtime, but a readable name ("Chest - Western Woods North") has to come from
the decomp tables: gKinstoneWorldEvents (src/common.c) maps a kinstone id to
a world event, and gWorldEvents (src/gameData.c) gives that event's type and
room. The EU/JP twins use the same kinstone -> world event mapping, so the
USA tables name every region.

    python3 tools/gen_tracker_fusions.py > port/port_tracker_fusions.inc
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Fusions 1..9 are the gold ones with no world event of their own.
GOLD = {
    1: "Mysterious Clouds (top right)",
    2: "Mysterious Clouds (bottom left)",
    3: "Mysterious Clouds (top left)",
    4: "Mysterious Clouds (middle)",
    5: "Mysterious Clouds (bottom right)",
    6: "Castor Wilds statue (left)",
    7: "Castor Wilds statue (middle)",
    8: "Castor Wilds statue (right)",
    9: "Source of the Flow",
}

# Types 4-18 were named from before/after captures of each fusion's spot
# (TMC_REPRO_TRACKER_SHOTS=1 in port_repro_tracker.c). Types whose captures
# showed nothing clear stay "Event".
KIND = {
    "WORLD_EVENT_TYPE_1": "Golden enemy",
    "WORLD_EVENT_TYPE_2": "Chest",
    "WORLD_EVENT_TYPE_3": "Butterfly",
    "WORLD_EVENT_TYPE_4": "Shallows",
    "WORLD_EVENT_TYPE_5": "Stairs down",
    "WORLD_EVENT_TYPE_6": "Tree stump",
    "WORLD_EVENT_TYPE_7": "Door in a tree",
    "WORLD_EVENT_TYPE_11": "Lily pads",
    "WORLD_EVENT_TYPE_18": "Gorons",
    "WORLD_EVENT_TYPE_BEANSTALK": "Beanstalk",
}


def table(text, name):
    start = text.index(name + "[] = {")
    return usa_lines(text[start : text.index("};", start)])


def usa_lines(text):
    """Keep what the USA build compiles. The tables only branch on
    `#ifdef DEMO_JP` and `#if defined(EU) || defined(JP) || defined(DEMO_JP)`,
    both false for USA."""
    keep = [True]
    out = []
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("#if"):
            if stripped not in ("#ifdef DEMO_JP", "#if defined(EU) || defined(JP) || defined(DEMO_JP)"):
                raise SystemExit(f"unhandled directive: {stripped}")
            keep.append(False)
        elif stripped.startswith("#else"):
            keep[-1] = not keep[-1]
        elif stripped.startswith("#endif"):
            keep.pop()
        elif all(keep):
            out.append(line)
    return "\n".join(out)


def main():
    common = open(os.path.join(ROOT, "src/common.c")).read()
    game_data = open(os.path.join(ROOT, "src/gameData.c")).read()

    kinstones = [
        tuple(int(v) for v in row.split(","))
        for row in re.findall(r"\{\s*([\d,\s]+)\}", table(common, "const KinstoneWorldEvent gKinstoneWorldEvents"))
    ]
    events = re.findall(
        r"\{\s*(WORLD_EVENT_TYPE_\w+)\s*,\s*([^,]+),\s*(\w+)\s*,\s*(\w+)\s*,[^}]*?,\s*CND_\d+\s*,\s*\w+\s*,\s*(\w+)\s*\}",
        table(game_data, "const WorldEvent gWorldEvents"),
        re.S,
    )

    out = sys.stdout
    out.write("/* Generated by tools/gen_tracker_fusions.py. Do not edit. */\n")
    out.write("/* Indexed by kinstone id; entry 0 is unused. */\n")
    out.write("static const char* const kTrackerFusionNames[101] = {\n")
    out.write('    "",\n')
    for kid in range(1, 101):
        if kid in GOLD:
            label = "Gold: " + GOLD[kid]
        else:
            ev_type, _entity, area, room, flag = events[kinstones[kid][4]]
            kind = KIND.get(ev_type, "Event")
            if flag.startswith("ITEM_SKILL_"):
                kind = "Waterfall to a Blade Brother"
            prefix = "ROOM_" + area[len("AREA_") :] + "_"
            place = room[len(prefix) :] if room.startswith(prefix) else room[len("ROOM_") :]
            place = place.replace("_", " ").title()
            # An area's main room (or none) adds nothing: the tracker groups
            # fusions under their area already.
            label = kind if place in ("Main", "0") else f"{kind} - {place}"
        out.write(f'    "{label}",\n')
    out.write("};\n")

    for kind, header, start, array in (
        ("NPC", "include/npc.h", "enum NPC {", "kTrackerNpcNames"),
        ("enemy", "include/enemy.h", "    /*0x00*/ OCTOROK,", "kTrackerEnemyNames"),
    ):
        text = open(os.path.join(ROOT, header)).read()
        i = text.index(start)
        block = text[i : text.index("}", i)]
        names = re.findall(r"/\*0x([0-9a-fA-F]+)\*/\s*(\w+)", block)
        out.write(f"/* {kind} ids, from {header}. */\n")
        out.write(f"static const char* const {array}[{len(names)}] = {{\n")
        for n, (value, name) in enumerate(names):
            assert int(value, 16) == n, (header, name)
            out.write(f'    "{pretty_entity(name)}",\n')
        out.write("};\n")


def pretty_entity(name):
    # Placeholder ids in the decomp, and one typo, would read as noise.
    if re.match(r"(NPC_UNK|NPC_NONE|ENEMY)_\w+$", name):
        return "Someone"
    name = {"TPWNSPERSON": "TOWNSPERSON"}.get(name, name)
    return name.replace("_", " ").title()


if __name__ == "__main__":
    main()
